using UnityEngine;
using System.Collections;

public class DatabaseItem
{
	#region GUI Data
		
	
	/// <summary>
	/// Atlas used for the item's icon.
	/// </summary>
	public UIAtlas iconAtlas;
	
	/// <summary>
	/// Name of the icon's sprite within the atlas.
	/// </summary>
	public string iconName = "";
	
	
	#endregion
	
	#region Game Data
	
	
	/// <summary>
	/// 16-bit item ID, generated by the system.
	/// Not to be confused with a 32-bit item ID, which actually contains the ID of the database as its prefix.
	/// </summary>
	public int id16;
	
	/// <summary>
	/// Name of this item.
	/// </summary>
	public string name;
	
	/// <summary>
	/// This item's custom description.
	/// </summary>
	public string description;


	#endregion
}